### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by beyarkay** [confluence/loadshedding#6]
Hi there! 

Your repo was pointed out to me in [this issue](https://github.com/beyarkay/eskom-calendar/issues/99#issuecomment-1263373542) on my own project, it appears we had similar ideas wrt getting loadshedding in our calendars.

There's no real issue here, just thought I'd reach out and say hi. Hi!

**Comment by confluence** [comment]
Hi! Feel free to cannibalise the algorithm from my script. :) If you look through the commits, you'll see that Cape Town's schedule has a weird and annoying irregularity in the later stages which breaks the nice pattern.

**Comment by beyarkay** [comment]
Okay thanks! That's interesting that there's a pattern at all to be honest, I just kinda assumed there was no consistency and wrote a PDF/HTML scraper to get the schedules that way. It's a pity there's no actual regularity behind these things though.
